export const userFeatures = [
  'Account – Authorization Codes',
  'ANI/CLI Customizations',
  'Anonymous Call Rejection',
  'Authentication by Digest',
  'Busy Lamp Field',
  'Call Forwarding',
  'Call Forwarding Always',
  'Call Forwarding Busy',
  'Call Forwarding No Answer',
  'Call Forwarding Not Reachable',
  'Find Me (Multiple numbers)',
  'Sync with Server',
  'Call Logs (Inbound and Outbound)',
  'Call Monitoring',
  'Automatic Recording',
  'Supervising Mode',
  'Silent Monitoring',
  'Call Notify',
  'Call Pick Up',
  'Call Pick Up Department',
  'Call Pick Up Domain',
  'Direct Call Pickup',
  'Call Recording',
  'Call Return',
  'Call Park with Ringback',
  'Call Status (Real-time in User Portal)',
  'Call Transfer',
  'Attend Transfer',
  'Blind Transfer',
  'Intercom Transfer',
  'Transfer to Voicemail',
  'Call Waiting',
  'Calling Line ID Delivery Blocking',
  'Calling Name Retrieval',
  'CDRs',
  'Charge or Billing Number',
  'Client Call Control (API and User Portal)',
  'Conferencing (Multi-Way Calling)',
  'Convene Conference',
]

export const systemFeatures = [
  'Brandable Portals',
  'All User Levels',
  'Configurable Permissions',
  'Custom Domains',
  'Secure',
  'Custom Integrations',
  'Salesforce Adapter',
  'Virtual Office Control Panel',
  'Hospitality and Resort Systems (PMS)',
  'Click-to-Call from WordPress and other CMS',
  'API',
  'Access all System Functions',
  'Call Control',
  'Configurable OAuth Permissions',
  'Event Subscriptions (webhook)',
  'Mature and Well Documented',
  'Fault Tolerant',
  'Active-Active Architecture',
  'Geo-distributed',
  'Highly Scalable',
  'Rolling and Hitless upgrades',
  'Security and Fraud Detection',
  'Auto Block Failed Registrations',
  'Auto Block SIP Port Scanning',
  'Auto Block Promiscuous SIP Devices',
  'Velocity Filter for Bad Digits',
  'Device Provisioning',
  'Customized Directories',
  'Domain and Device Overrides',
  'MAC Management',
  'Remotely Triggered Updates',
  'Supports Major SIP Phones',
  'Zero Touch Device Configuration',
  'Regulatory Compliance',
  '911 Emergency Calling Solution',
  'CALEA (lawful intercept)',
]

export const groupFeatures = [
  'ACD',
  'Auto Attendants',
  'Personal Auto Attendants',
  'Scheduled Auto Attendant',
  'Chained Auto Attendants',
  'Barge In',
  'Business Trunking',
  'Call Intercept',
  'Call Park',
  'Directed',
  'Dynamic',
  'Calling Group ID Delivery',
  'Configurable Extension Dialing',
  'Configurable Feature Codes',
  'Configurable Directories',
  'Device Inventory',
  'Department Support',
  'Group Announcements',
  'Group Custom Ringback',
  'Group Instant Messaging',
  'Hot Desking',
  'Hoteling',
  'Hunt Groups',
  'Instant Group Call',
  'Listen In',
  'Office Manager Portal (Web Portal)',
  'Active Calls',
  'Auto Attendant Designer',
  'Call Records',
  'Call Statistics',
  'Conference Bridge Configuration',
  'Device Provisioning',
  'Moves, Adds, Changes',
  'Music on Hold Upload',
  'Queue Management',
  'Voicemail Management',
  'Night Mode',
  'Paging',
  'Simultaneous Ring (Group)',
  'Invite Attendees',
  'Multiple Conference Rooms',
  'Scheduled/Instant Conference',
  'Web-based Setup',
  'Device Auto Provisioning',
  'Direct Inward Dialing',
  'Directed Call Park',
  'Dynamic Call Park',
  'Directed Call Pickup',
  'Diversion Inhibitor',
  'Do Not Disturb',
  'Sync with Server',
  'Extension Dialing',
  'External Calling Line ID Delivery',
  'In-Call Service Activation',
  'Instant Messaging (via XMPP or SIP SIMPLE)',
  'Intercom',
  'Internal Calling Line ID Delivery',
  'Last Number Redial',
  'Message Waiting Indicator',
  'Music On-Hold',
  'System Default Music-on-Hold',
  'Personalized Music-on-Hold',
  'Phone Status',
  'Presence',
  'Privacy',
  'Selective Call Acceptance',
  'Selective Call Rejection',
  'Simultaneous Ring',
  'Shared Call Appearance',
  'Three-Way Call',
  'Two-Stage Dialing',
  'Video Telephony',
  'Voicemail',
  'Default Greetings',
  'Customizable Greetings',
  'Name Recording',
  'Email Notification',
  'Voicemail Forwarding',
  'Forwarding Email',
  'User Portal (View, Save, Delete)',
  'Voice Messaging Group',
  'Voice Messaging Call Back',
  'Web User Portal',
  'Contact List with Presence',
  'Click to Call',
  'Inbound Call Handling Rules',
  'Screen Pops',
  'Messaging',
]
